language: c
compiler:
  - gcc

os:
  - linux
  
script:
  - curl -Ls https://git.io/ttask.sh | sh
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
  - "./bin/task ci"
